# Generated by Django 3.2.15 on 2022-10-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_xu3ixd', upload_to='images/'),
        ),
    ]
